// Mocks generated by Mockito 5.4.4 from annotations
// in nepalink/test/features/dashboard/tasks/presentation/view_model/task_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nepalink/core/errors/failures.dart' as _i5;
import 'package:nepalink/features/dashboard/tasks/domain/entities/task_entity.dart'
    as _i6;
import 'package:nepalink/features/dashboard/tasks/domain/usecases/create_task_usecase.dart'
    as _i7;
import 'package:nepalink/features/dashboard/tasks/domain/usecases/delete_task_usecase.dart'
    as _i9;
import 'package:nepalink/features/dashboard/tasks/domain/usecases/get_tasks_for_nurse_usecase.dart'
    as _i3;
import 'package:nepalink/features/dashboard/tasks/domain/usecases/update_task_status_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTasksForNurseUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTasksForNurseUsecase extends _i1.Mock
    implements _i3.GetTasksForNurseUsecase {
  MockGetTasksForNurseUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TaskEntity>>> call(
          String? nurseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [nurseId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.TaskEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TaskEntity>>(
          this,
          Invocation.method(
            #call,
            [nurseId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.TaskEntity>>>);
}

/// A class which mocks [CreateTaskUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTaskUsecase extends _i1.Mock implements _i7.CreateTaskUsecase {
  MockCreateTaskUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>> call(
          _i6.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [task],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.TaskEntity>(
          this,
          Invocation.method(
            #call,
            [task],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>);
}

/// A class which mocks [UpdateTaskStatusUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTaskStatusUsecase extends _i1.Mock
    implements _i8.UpdateTaskStatusUsecase {
  MockUpdateTaskStatusUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>> call(
          _i8.UpdateTaskStatusParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.TaskEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TaskEntity>>);
}

/// A class which mocks [DeleteTaskUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTaskUsecase extends _i1.Mock implements _i9.DeleteTaskUsecase {
  MockDeleteTaskUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> call(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [taskId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [taskId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
