// Mocks generated by Mockito 5.4.4 from annotations
// in nepalink/test/features/dashboard/profile/presentation/view_model/profile_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nepalink/core/errors/failures.dart' as _i5;
import 'package:nepalink/core/services/storage/user_session_service.dart'
    as _i7;
import 'package:nepalink/features/dashboard/profile/domain/entities/profile_entity.dart'
    as _i6;
import 'package:nepalink/features/dashboard/profile/domain/usecases/profile_usecases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetProfileUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUsecase extends _i1.Mock implements _i3.GetProfileUsecase {
  MockGetProfileUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>> call(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.ProfileEntity>(
          this,
          Invocation.method(
            #call,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>);
}

/// A class which mocks [UpdateProfileUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUsecase extends _i1.Mock
    implements _i3.UpdateProfileUsecase {
  MockUpdateProfileUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>> call(
          _i3.UpdateProfileParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.ProfileEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>);
}

/// A class which mocks [UploadProfilePictureUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProfilePictureUsecase extends _i1.Mock
    implements _i3.UploadProfilePictureUsecase {
  MockUploadProfilePictureUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>> call(
          _i3.UploadPictureParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.ProfileEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileEntity>>);
}

/// A class which mocks [LogoutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUsecase extends _i1.Mock implements _i3.LogoutUsecase {
  MockLogoutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [UserSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSessionService extends _i1.Mock
    implements _i7.UserSessionService {
  MockUserSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUserSession({
    required String? userId,
    required String? name,
    required String? email,
    required String? phone,
    required String? password,
    String? profilePic,
    String? token,
    String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserSession,
          [],
          {
            #userId: userId,
            #name: name,
            #email: email,
            #phone: phone,
            #password: password,
            #profilePic: profilePic,
            #token: token,
            #role: role,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfilePic(String? profilePic) => (super.noSuchMethod(
        Invocation.method(
          #updateProfilePic,
          [profilePic],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRole(String? role) => (super.noSuchMethod(
        Invocation.method(
          #updateRole,
          [role],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
