// Mocks generated by Mockito 5.4.4 from annotations
// in nepalink/test/features/dashboard/notification/presentation/view_model/notification_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nepalink/core/errors/failures.dart' as _i5;
import 'package:nepalink/features/dashboard/notification/domain/entities/notification_entity.dart'
    as _i6;
import 'package:nepalink/features/dashboard/notification/domain/usecases/notification_usecases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetNotificationsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotificationsUsecase extends _i1.Mock
    implements _i3.GetNotificationsUsecase {
  MockGetNotificationsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.NotificationEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, List<_i6.NotificationEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.NotificationEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.NotificationEntity>>>);
}

/// A class which mocks [MarkAsReadUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkAsReadUsecase extends _i1.Mock implements _i3.MarkAsReadUsecase {
  MockMarkAsReadUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call(String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [notificationId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #call,
            [notificationId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [MarkAllAsReadUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkAllAsReadUsecase extends _i1.Mock
    implements _i3.MarkAllAsReadUsecase {
  MockMarkAllAsReadUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
