// Mocks generated by Mockito 5.4.4 from annotations
// in nepalink/test/features/auth/presentation/pages/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:local_auth/local_auth.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nepalink/core/errors/failures.dart' as _i6;
import 'package:nepalink/core/services/biometric/biometric_service.dart' as _i3;
import 'package:nepalink/core/services/storage/user_session_service.dart'
    as _i8;
import 'package:nepalink/features/auth/domain/entities/user_entity.dart' as _i7;
import 'package:nepalink/features/auth/domain/usecases/login_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBiometricResult_1 extends _i1.SmartFake
    implements _i3.BiometricResult {
  _FakeBiometricResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUsecase extends _i1.Mock implements _i4.LoginUsecase {
  MockLoginUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.UserEntity>> call(
          _i4.LoginParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [UserSessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSessionService extends _i1.Mock
    implements _i8.UserSessionService {
  MockUserSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveUserSession({
    required String? userId,
    required String? name,
    required String? email,
    required String? phone,
    required String? password,
    String? profilePic,
    String? token,
    String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserSession,
          [],
          {
            #userId: userId,
            #name: name,
            #email: email,
            #phone: phone,
            #password: password,
            #profilePic: profilePic,
            #token: token,
            #role: role,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfilePic(String? profilePic) => (super.noSuchMethod(
        Invocation.method(
          #updateProfilePic,
          [profilePic],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRole(String? role) => (super.noSuchMethod(
        Invocation.method(
          #updateRole,
          [role],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i3.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i9.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableBiometrics,
          [],
        ),
        returnValue:
            _i5.Future<List<_i9.BiometricType>>.value(<_i9.BiometricType>[]),
      ) as _i5.Future<List<_i9.BiometricType>>);

  @override
  _i5.Future<bool> isBiometricEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.BiometricResult> enableBiometric() => (super.noSuchMethod(
        Invocation.method(
          #enableBiometric,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BiometricResult>.value(_FakeBiometricResult_1(
          this,
          Invocation.method(
            #enableBiometric,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BiometricResult>);

  @override
  _i5.Future<void> disableBiometric() => (super.noSuchMethod(
        Invocation.method(
          #disableBiometric,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.BiometricResult> authenticate(
          {String? reason = r'Please authenticate to continue'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {#reason: reason},
        ),
        returnValue:
            _i5.Future<_i3.BiometricResult>.value(_FakeBiometricResult_1(
          this,
          Invocation.method(
            #authenticate,
            [],
            {#reason: reason},
          ),
        )),
      ) as _i5.Future<_i3.BiometricResult>);

  @override
  _i5.Future<void> saveEmailForBiometric(String? email) => (super.noSuchMethod(
        Invocation.method(
          #saveEmailForBiometric,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getSavedEmail() => (super.noSuchMethod(
        Invocation.method(
          #getSavedEmail,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> cancelAuthentication() => (super.noSuchMethod(
        Invocation.method(
          #cancelAuthentication,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
